#!/bin/sh
# Author: Rémi BARBERO
# Date: 2017-04-14
# Mail: rems14@remibarbero.fr
# Incremental backups with rsync and hard links

# include local configuration
if [ -f 'ib.cfg' ]; then
    . ./ib.cfg
else
    exit 1
fi

# test variables in config.cfg
# SOURCE_PATH must be not empty
if [ ${#SOURCE_PATH[*]} -eq 0 ]; then
    echo 'error: SOURCE_PATH is not defined.'
    exit 1
fi
# DEST_PATH must be defined
if [ -z $DEST_PATH ]; then
    echo 'error: DEST_PATH_PATH is no defined.'
    exit 1
fi
# START_NUMBER must be defined
if [ -z $START_NUMBER ]; then
    echo 'error: START_NUMBER is not defined.'
    exit 1
fi
# NUMBER_BACKUP must be not empty
if [ $NUMBER_BACKUP -eq 0 ]; then
    echo 'error: NUMBER_BACKUP is not defined.'
    exit 1
fi
# TIME_BACKUP must be not empty
if [ $TIME_BACKUP -eq 0 ]; then
    echo 'error: TIME_BACKUP is not defined.'
    exit 1
fi

DEST_RSYNC_FOLDER="0_`date +%Y%m%d`"

# ssh commands manage the stock of backups
# Arguments: PATH OFFSET_START NUMBER_OF_BACKUP +INTERVAL_TIME(n * 24h)
manage_save.sh $DEST_PATH $START_NUMBER $DAILY_NUMBER $TIME_BACKUP

#rsync
for i in "${SOURCE_PATH[@]}"
do
    rsync -a --delete ${EXCLUDES[@]/#/--exclude=} "$i" $DEST_PATH/$DEST_RSYNC_FOLDER/
done
